name: CI
env:
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
on:
  pull_request:
    types: [labeled, synchronize, edited]
    branches:
      - main
    paths-ignore:
      - ".nxignore"

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    if: "${{ contains(github.event.pull_request.labels.*.name, 'PR status: review ready') }}"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.19.1"
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        shell: bash
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        shell: bash
      - name: Setup Canvas
        run: npm rebuild canvas
      - name: Run test
        run: yarn test
